name: cd

on:
  push:
    branches:
      - master
      - develop

env: 
  AWS_REGION: eu-west-3

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'

    steps:
    - name: Clone
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Define variables
      run: |
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: Publish on prod
      if: github.ref == 'refs/heads/master'
      run: ./publish.sh prod

    - name: Publish on dev
      if: github.ref == 'refs/heads/develop'
      run: ./publish.sh dev